# Generated by Django 4.0.1 on 2022-01-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_rename_produto_produtos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
