# Generated by Django 4.0.1 on 2022-03-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0022_alter_cliente_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='EstCivil',
            field=models.IntegerField(choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)'), (4, 'Viúvo(a)'), (5, 'Desquitado(a)'), (6, 'União Estável')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='carro',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='filhos',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nasc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
