# Generated by Django 4.0.1 on 2022-03-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_estadocivil_alter_cliente_estcivil_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadocivil',
            table='estado_civil',
        ),
    ]
