# Generated by Django 4.0.1 on 2022-03-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0024_alter_estadocivil_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='EstCivil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.estadocivil'),
            preserve_default=False,
        ),
    ]
