# Generated by Django 4.0.1 on 2022-01-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_rename_produtos_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
