# Generated by Django 4.0.1 on 2022-02-06 17:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='carro',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estadoCivil',
            field=models.IntegerField(choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Divorcido(a)'), (4, 'Viuvo(a)'), (5, 'Desquitado(a)'), (6, 'União Estável')], default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='filho',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
