# Generated by Django 4.0.1 on 2022-02-06 18:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_cliente_carro_cliente_estadocivil_cliente_filho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carro',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.IntegerField(choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Divorcido(a)'), (4, 'Viuvo(a)'), (5, 'Desquitado(a)'), (6, 'União Estável')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='filho',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
