# Generated by Django 4.0.1 on 2022-02-06 18:19

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_cliente_carro_alter_cliente_data_nasc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpfcnpj',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.tppessoa'),
        ),
    ]
