# Generated by Django 4.0.1 on 2022-02-06 18:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_data_nasc_alter_cpfcnpj_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carro',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.IntegerField(blank=True, choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Divorcido(a)'), (4, 'Viuvo(a)'), (5, 'Desquitado(a)'), (6, 'União Estável')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='filho',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
