# Generated by Django 4.0.1 on 2022-03-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_uf_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='estadoCivil',
            new_name='estado_civil',
        ),
    ]
